services:
  aeroplane-app:
    image: ghcr.io/mondychan/aeroplane-app:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3010:3000"
    env_file:
      - path: .env
        required: false
    volumes:
      - aeroplane-data:/app/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

volumes:
  aeroplane-data:

